[package]
name = "deck-gl-examples"
description = "Examples for deck.gl-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
math-gl = { workspace = true }
luma-gl = { workspace = true }
deck-gl = { workspace = true, features = ["png"] }
deck-gl-layers = { workspace = true }
deck-gl-json = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
image = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
arrow-ipc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
winit = "0.30"
egui = "0.32.3"
egui-wgpu = "0.32.3"
egui-winit = "0.32.3"
